name: app_pages
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  fluro: "^1.4.0" # 路由库
  shared_preferences: ^0.5.1+1 #数据共享
  dio: ^2.1.0  # 网络请求 
  flutter_easyrefresh: ^1.2.7 # 下拉刷新辅助
  flutter_swiper : ^1.1.6
  device_info : ^0.2.0 # 设备信息
  # amap_base: # 地图
  #   git:
  #     url: https://github.com/yohom/amap_base_flutter.git
  #     ref: android-support-library
  #     path: base
  # 按需引入地图模块
  # amap_base_map: ^0.3.4
  # amap_base_location: ^0.3.4
  vibrate: ^0.0.4 # 震动权限
  fluttery_seekbar: ^0.0.1
  # barcode_scan: ^0.0.4 # 二维码扫描
  flutter_screenutil: ^0.5.2 # 屏幕适配

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/logo.png
  - assets/images/bg.jpg
  - assets/images/sun.png
  - assets/images/nike_logo.jpg
  # 示例页面图片
  - assets/images/screens/guide_page.png
  - assets/images/screens/shopping_page.png
  - assets/images/screens/card_page.png
  # assets/分类图片
  - assets/images/cats/001.png
  - assets/images/cats/002.png
  - assets/images/cats/003.png
  - assets/images/cats/004.png
  - assets/images/cats/005.png
  - assets/images/cats/006.png
  - assets/images/cats/007.png
  - assets/images/cats/008.png
  - assets/images/cats/009.png
  - assets/images/cats/010.png
  - assets/images/cats/011.png
  # 地图相关图片
  - assets/images/default_marker.png
  # 卡片图片
  - assets/images/cards/01.png
  - assets/images/cards/02.png
  - assets/images/cards/03.png
  - assets/images/cards/04.png
  # nike 图片
  - assets/images/nike/shoes.png
  - assets/images/nike/shoes02.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Iconfonts
      fonts:
        - asset: assets/iconfonts/iconfont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
